version: "3.8"

services:
  email-verifier:
    image: sabarinathan1611/email-verifier:latest
    build: .
    container_name: email-verifier
    ports:
      - "${PORT:-80}:80"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-80}
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - email-network

  mongodb:
    image: mongo:7.0
    container_name: email-verifier-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - email-network

volumes:
  mongodb_data:

networks:
  email-network:
    driver: bridge
